"""baseline schema

Revision ID: 5526a181197b
Revises: 
Create Date: 2026-04-16 18:42:46.750993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5526a181197b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('chat_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_entry_date'), 'entries', ['entry_date'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stt_base_url', sa.String(), nullable=True),
    sa.Column('stt_api_key_wrapped', sa.String(), nullable=True),
    sa.Column('stt_model', sa.String(), nullable=True),
    sa.Column('chat_base_url', sa.String(), nullable=True),
    sa.Column('chat_api_key_wrapped', sa.String(), nullable=True),
    sa.Column('chat_model', sa.String(), nullable=True),
    sa.Column('embed_base_url', sa.String(), nullable=True),
    sa.Column('embed_api_key_wrapped', sa.String(), nullable=True),
    sa.Column('embed_model', sa.String(), nullable=True),
    sa.Column('tts_base_url', sa.String(), nullable=True),
    sa.Column('tts_api_key_wrapped', sa.String(), nullable=True),
    sa.Column('tts_model', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('totp_pending_secret', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('entry_tags',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_name'], ['tags.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'tag_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_tags')
    op.drop_table('tags')
    op.drop_table('settings')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_entries_entry_date'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
