"""add tts_voice and tts_speed to settings

Revision ID: e3cb482e6e29
Revises: 5526a181197b
Create Date: 2026-04-16 22:33:55.544136

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3cb482e6e29'
down_revision: str | Sequence[str] | None = '5526a181197b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('tts_voice', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('tts_speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'tts_speed')
    op.drop_column('settings', 'tts_voice')
    # ### end Alembic commands ###
